### ISSUE TITLE
Debug issue with animated GIFs, report to rust-image

### ISSUE THREAD

**Issue by cybergeek94** [cybergeek94/img-dup#2]
Don't have the error message on hand, but it was an index out of bounds error when iterating the pixels of an image. For some reason, the internal vector length of the `ImageBuf` did not match `width * height` and so the iterator was going past the end. I was able to reduce the problem domain to certain animated GIFs, though I cannot provide the images I used for personal reasons.

**Comment by abonander** [comment]
Looks like this was fixed some time ago.
